[env:lilygo-t-display-s3]
platform = espressif32@6.6.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
upload_port = COM16
monitor_port = COM16
monitor_speed = 115200

build_flags =
    -DARDUINO_ESP32S3_DEV
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; TFT_eSPI Setup206 — LilyGo T-Display-S3, 8-bit parallel ST7789, 170x320
    -DUSER_SETUP_LOADED=1
    -DUSER_SETUP_ID=206
    -DST7789_DRIVER=1
    -DINIT_SEQUENCE_3=1
    -DCGRAM_OFFSET=1
    -DTFT_RGB_ORDER=0
    -DTFT_INVERSION_ON=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=5
    -DTFT_WR=8
    -DTFT_RD=9
    -DTFT_D0=39
    -DTFT_D1=40
    -DTFT_D2=41
    -DTFT_D3=42
    -DTFT_D4=45
    -DTFT_D5=46
    -DTFT_D6=47
    -DTFT_D7=48
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=1
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient @ ^3.2.1
    PaulStoffregen/Time @ ^1.6.1
